### ISSUE TITLE
Issue with Ray=1.2.0

### ISSUE THREAD

**Issue by richardlin047** [modin-project/qgrid#11]
`modin_spreadsheet` works with Ray=1.1.0 but not Ray=1.2.0
In Jupyter notebook, the kernel dies when `spreadsheet = modin_spreadsheet.show_grid(df, show_toolbar=True, grid_options={'forceFitColumns': False})` called
There's no obvious error in the browser console or notebook server log

When running pytest, all tests fail due to `Broken Pipe`. 

More investigation needs to be done

**Comment by richardlin047** [comment]
Seems to be a Modin compatibility issue, same error occurs here: https://github.com/modin-project/modin/issues/2761#issuecomment-782583595

```javascript
(raylet) [2021-02-23 00:25:47,462 C 13930 2446768] pull_manager.cc:246:  Check failed: it != object_pull_requests_.end() 
(raylet) [2021-02-23 00:25:47,462 E 13930 2446768] logging.cc:415: *** Aborted at 1614057947 (unix time) try "date -d @1614057947" if you are using GNU date ***
(raylet) [2021-02-23 00:25:47,462 E 13930 2446768] logging.cc:415: PC: @                0x0 (unknown)
(raylet) [2021-02-23 00:25:47,462 E 13930 2446768] logging.cc:415: *** SIGABRT (@0x7fff6b34933a) received by PID 13930 (TID 0x10e1eedc0) stack trace: ***
(raylet) [2021-02-23 00:25:47,462 E 13930 2446768] logging.cc:415:     @     0x7fff6b3fa5fd _sigtramp
(raylet) [2021-02-23 00:25:47,463 E 13930 2446768] logging.cc:415:     @        0x10cfcf008 absl::lts_2019_08_08::AlphaNum::AlphaNum()::hexdigits
(raylet) [2021-02-23 00:25:47,463 E 13930 2446768] logging.cc:415:     @     0x7fff6b2d0808 abort
(raylet) [2021-02-23 00:25:47,463 E 13930 2446768] logging.cc:415:     @        0x10c8cafba ray::SpdLogMessage::Flush()
(raylet) [2021-02-23 00:25:47,463 E 13930 2446768] logging.cc:415:     @        0x10c8a1fb9 ray::RayLog::~RayLog()
(raylet) [2021-02-23 00:25:47,463 E 13930 2446768] logging.cc:415:     @        0x10c5730f9 ray::PullManager::CancelPull()
(raylet) [2021-02-23 00:25:47,463 E 13930 2446768] logging.cc:415:     @        0x10c53944a ray::ObjectManager::CancelPull()
(raylet) [2021-02-23 00:25:47,463 E 13930 2446768] logging.cc:415:     @        0x10c4456be ray::raylet::DependencyManager::RemoveTaskDependencies()
(raylet) [2021-02-23 00:25:47,463 E 13930 2446768] logging.cc:415:     @        0x10c4f4c39 ray::raylet::ClusterTaskManager::DispatchScheduledTasksToWorkers()
(raylet) [2021-02-23 00:25:47,463 E 13930 2446768] logging.cc:415:     @        0x10c4f678d ray::raylet::ClusterTaskManager::QueueAndScheduleTask()
(raylet) [2021-02-23 00:25:47,463 E 13930 2446768] logging.cc:415:     @        0x10c47096e ray::raylet::NodeManager::HandleRequestWorkerLease()
(raylet) [2021-02-23 00:25:47,464 E 13930 2446768] logging.cc:415:     @        0x10c4ae9a2 ray::rpc::ServerCallImpl<>::HandleRequestImpl()
(raylet) [2021-02-23 00:25:47,464 E 13930 2446768] logging.cc:415:     @        0x10c4ae8e4 _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc14ServerCallImplINS4_25NodeManagerServiceHandlerENS4_25RequestWorkerLeaseRequestENS4_23RequestWorkerLeaseReplyEE13HandleRequestEvEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
(raylet) [2021-02-23 00:25:47,464 E 13930 2446768] logging.cc:415:     @        0x10cd389b3 boost::asio::detail::scheduler::do_run_one()
(raylet) [2021-02-23 00:25:47,464 E 13930 2446768] logging.cc:415:     @        0x10cd2c7f2 boost::asio::detail::scheduler::run()
(raylet) [2021-02-23 00:25:47,464 E 13930 2446768] logging.cc:415:     @        0x10cd2c68b boost::asio::io_context::run()
(raylet) [2021-02-23 00:25:47,464 E 13930 2446768] logging.cc:415:     @        0x10c423518 main
(raylet) [2021-02-23 00:25:47,464 E 13930 2446768] logging.cc:415:     @     0x7fff6b201cc9 start
Traceback (most recent call last):
  File "/Users/richard/Documents/modin-spreadsheet/qgrid/richard_test.py", line 26, in <module>
    sheet = modin_spreadsheet.show_grid(df)
  File "/Users/richard/Documents/modin-spreadsheet/qgrid/modin_spreadsheet/grid.py", line 512, in show_grid
    return SpreadsheetWidget(
  File "/Users/richard/Documents/modin-spreadsheet/qgrid/modin_spreadsheet/grid.py", line 631, in __init__
    self._update_df()
  File "/Users/richard/Documents/modin-spreadsheet/qgrid/modin_spreadsheet/grid.py", line 823, in _update_df
    self._df.insert(0, self._index_col_name, range(0, len(self._df)))
  File "/Users/richard/.pyenv/versions/modin-spreadsheet/lib/python3.8/site-packages/modin/pandas/dataframe.py", line 960, in insert
    new_query_compiler = self._query_compiler.insert(loc, column, value)
  File "/Users/richard/.pyenv/versions/modin-spreadsheet/lib/python3.8/site-packages/modin/backends/pandas/query_compiler.py", line 2307, in insert
    new_modin_frame = self._modin_frame._apply_full_axis_select_indices(
  File "/Users/richard/.pyenv/versions/modin-spreadsheet/lib/python3.8/site-packages/modin/engines/base/frame/data.py", line 1396, in _apply_full_axis_select_indices
    self._frame_mgr_cls.apply_func_to_select_indices_along_full_axis(
  File "/Users/richard/.pyenv/versions/modin-spreadsheet/lib/python3.8/site-packages/modin/engines/base/frame/partition_manager.py", line 816, in apply_func_to_select_indices_along_full_axis
    preprocessed_func = cls.preprocess_func(func)
  File "/Users/richard/.pyenv/versions/modin-spreadsheet/lib/python3.8/site-packages/modin/engines/base/frame/partition_manager.py", line 56, in preprocess_func
    return cls._partition_class.preprocess_func(map_func)
  File "/Users/richard/.pyenv/versions/modin-spreadsheet/lib/python3.8/site-packages/modin/engines/ray/pandas_on_ray/frame/partition.py", line 155, in preprocess_func
    return ray.put(func)
  File "/Users/richard/.pyenv/versions/modin-spreadsheet/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/Users/richard/.pyenv/versions/modin-spreadsheet/lib/python3.8/site-packages/ray/worker.py", line 1489, in put
    object_ref = worker.put_object(value)
  File "/Users/richard/.pyenv/versions/modin-spreadsheet/lib/python3.8/site-packages/ray/worker.py", line 277, in put_object
    self.core_worker.put_serialized_object(
  File "python/ray/_raylet.pyx", line 994, in ray._raylet.CoreWorker.put_serialized_object
  File "python/ray/_raylet.pyx", line 918, in ray._raylet.CoreWorker._create_put_buffer
  File "python/ray/_raylet.pyx", line 153, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Broken pipe
```

**Comment by devin-petersohn** [comment]
Opened https://github.com/ray-project/ray/issues/14279 to track

**Comment by devin-petersohn** [comment]
Closing as we will fix this in Modin
