### ISSUE TITLE
No module named 'modin_spreadsheet'

### ISSUE THREAD

**Issue by rootsmusic** [modin-project/qgrid#51]
### Environment
* Operating System: Windows 10.0.22621
* Python Version: 3.10.11.final.0
`python                    3.10.11              h11da44f_0    intel`
* How did you install modin-spreadsheet: `pip install "modin[spreadsheet]"`
<summary> Python packages:</summary>
<details>

aiohttp==3.8.5
aiohttp-cors==0.7.0
aiosignal==1.3.1
ansicon==1.89.0
anyio==3.7.1
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asn1crypto @ file:///home/conda/feedstock_root/build_artifacts/asn1crypto_1647369152656/work
asttokens==2.2.1
async-lru==2.0.3
async-timeout==4.0.2
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
blessed==1.20.0
boto3==1.28.10
botocore==1.31.10
brotlipy @ file:///D:/bld/brotlipy_1666764804378/work
cachetools==5.3.1
certifi==2023.5.7
cffi @ file:///D:/bld/cffi_1671179506518/work
chardet @ file:///D:/bld/chardet_1669990505384/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1678108872112/work
click==8.1.6
cloudpickle==2.2.1
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
colorful==0.5.5
comm==0.1.3
conda_package_streaming @ file:///home/conda/feedstock_root/build_artifacts/conda-package-streaming_1685101166527/work
cryptography @ file:///D:/bld/cryptography-split_1685659586775/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
Cython @ file:///D:/bld/cython_1685025169174/work
dask==2023.7.1
debugpy==1.6.7
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.7
distributed==2023.7.1
dpcpp-llvm-spirv==0.0.0+dev
dpctl==0.14.5+24.g33c241c01
dpnp==0.12.1
exceptiongroup==1.1.2
executing==1.2.0
fastjsonschema==2.18.0
filelock==3.12.2
fqdn==1.5.1
frozenlist==1.4.0
fsspec==2023.6.0
funcsigs==1.0.2
google-api-core==2.11.1
google-auth==2.22.0
googleapis-common-protos==1.59.1
gpustat==1.1
grpcio==1.56.2
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
importlib-metadata==6.8.0
ipykernel==6.25.0
ipython==8.14.0
ipython-genutils==0.2.0
ipywidgets==7.0.0
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
jinxed==1.2.0
jmespath==1.0.1
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1663332044897/work
json5==0.9.14
jsonpatch @ file:///home/conda/feedstock_root/build_artifacts/jsonpatch_1632759296524/work
jsonpointer==2.0
jsonschema==4.18.4
jsonschema-specifications==2023.7.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter-lsp==2.2.0
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.7.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.3
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.8
jupyterlab_server==2.24.0
kiwisolver @ file:///D:/bld/kiwisolver_1666805768319/work
llvmlite==0.40.0
locket==1.0.0
MarkupSafe==2.1.3
matplotlib-inline==0.1.6
menuinst @ file:///D:/bld/menuinst_1666839998718/work
mistune==3.0.1
mkl-fft==1.3.6
mkl-random==1.2.2
mkl-service==2.4.0
mkl-umath==0.1.1
modin==0.23.0
modin-spreadsheet==0.1.2
mpi4py-mpich==3.1.2
msgpack==1.0.5
multidict==6.0.4
nbclient==0.8.0
nbconvert==7.7.3
nbformat==5.9.1
nest-asyncio==1.5.6
notebook==7.0.0
notebook_shim==0.2.3
numba @ file:///D:/bld/numba_1686793785624/work
numba-dpex==0.21.1+1.gffee89509
numpy==1.24.3
nvidia-ml-py==12.535.77
opencensus==0.11.2
opencensus-context==0.1.3
overrides==7.3.1
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas==2.0.3
pandocfilters==1.5.0
parso==0.8.3
partd==1.4.0
pickleshare==0.7.5
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1687097136512/work
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1667232663820/work
plumbum==1.8.2
pooch @ file:///home/conda/feedstock_root/build_artifacts/pooch_1679580333621/work
prometheus-client==0.17.1
prompt-toolkit==3.0.39
protobuf==4.23.4
psutil==5.9.5
pure-eval==0.2.2
py-spy==0.3.14
pyarrow==12.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pydantic==1.10.12
Pygments==2.15.1
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1685514481738/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1687132014935/work
PySocks @ file:///D:/bld/pysocks_1648857426124/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-json-logger==2.0.7
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
pywin32==304
pywinpty==2.0.11
PyYAML @ file:///D:/bld/pyyaml_1666772550103/work
pyzmq==25.1.0
qtconsole==5.4.3
QtPy==2.3.1
ray==2.6.1
referencing==0.30.0
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1684774241324/work
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.9.2
rpyc==4.1.5
rsa==4.9
ruamel.yaml @ file:///D:/bld/ruamel.yaml_1686994025923/work
ruamel.yaml.clib @ file:///D:/bld/ruamel.yaml.clib_1670412994006/work
s3transfer==0.6.1
scikit-learn @ file:///D:/bld/scikit-learn_1685023828887/work
scipy==1.10.1
Send2Trash==1.8.2
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smart-open==6.3.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.4.1
stack-data==0.6.2
TBB==0.2
tblib==2.0.0
terminado==0.17.1
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1643647933166/work
tinycss2==1.2.1
tomli==2.0.1
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1657485559105/work
tornado==6.3.2
traitlets==5.9.0
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1685704949284/work
tzdata==2023.3
unidist==0.4.1
uri-template==1.3.0
urllib3==1.26.16
virtualenv==20.21.0
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
widgetsnbextension==3.0.8
win-inet-pton @ file:///D:/bld/win_inet_pton_1666755058235/work
wincertstore==0.2
yarl==1.9.2
zict==3.0.0
zipp==3.16.2
zstandard==0.19.0
* Jupyter lab packages (if applicable):
JupyterLab v4.0.3
C:\ProgramData\Anaconda3\envs\DS\share\jupyter\labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        @jupyter-notebook/lab-extension v7.0.0 enabled ok
        @jupyter-widgets/jupyterlab-manager v5.0.8 enabled ok (python, jupyterlab_widgets)

</details>

### Description of Issue
Error after installing modin-spreadsheet when I followed README to execute `jupyter nbextension enable --py --sys-prefix modin_spreadsheet`:
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\Scripts\jupyter-nbextension-script.py", line 9, in <module>
>     sys.exit(main())
>   File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 277, in launch_instance
>     return super().launch_instance(argv=argv, **kwargs)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 1043, in launch_instance
>     app.start()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 972, in start
>     super().start()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in start
>     self.subapp.start()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 882, in start
>     self.toggle_nbextension_python(self.extra_args[0])
>   File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 855, in toggle_nbextension_python
>     return toggle(module,
>   File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 470, in enable_nbextension_python
>     return _set_nbextension_state_python(True, module, user, sys_prefix,
>   File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 368, in _set_nbextension_state_python
>     m, nbexts = _get_nbextension_metadata(module)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 1107, in _get_nbextension_metadata
>     m = import_item(module)
>   File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\utils\importstring.py", line 38, in import_item
>     return __import__(parts[0])
> ModuleNotFoundError: No module named 'modin_spreadsheet'

### Reproduction Steps
1. `pip install "modin[all]"`
2. `pip install --upgrade tornado>=6.2.0`
3. `pip install --upgrade jupyter-client>=7.4.4`
4. `pip install "modin[spreadsheet]"`
5. `pip install --upgrade ipywidgets==7.0.0`
6. `jupyter nbextension enable --py --sys-prefix modin_spreadsheet`
### What steps have you taken to resolve this already?
I downgraded ipywidgets, which was suggested by #49.

**Comment by rootsmusic** [comment]
See https://github.com/quantopian/qgrid/pull/331 that fixed this issue in qgrid.

**Comment by rootsmusic** [comment]
See #46

**Comment by rootsmusic** [comment]
Solution at #48
